name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Mark as prerelease'
        required: false
        type: boolean
        default: false

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        
    - name: Build and package all targets
      run: task package:all
      
    - name: Run validation checks
      run: task check:all
      
    - name: Create release archives
      run: |
        cd dist
        tar -czf ../typescript-client-${{ inputs.version }}.tar.gz typescript/
        tar -czf ../go-client-${{ inputs.version }}.tar.gz go/
        tar -czf ../openapi-specs-${{ inputs.version }}.tar.gz openapi/
        cp python-dist/*.whl ../python-client-${{ inputs.version }}.whl
        cp python-dist/*.tar.gz ../python-client-${{ inputs.version }}-source.tar.gz
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.version }}
        name: Release ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        generate_release_notes: true
        files: |
          typescript-client-${{ inputs.version }}.tar.gz
          go-client-${{ inputs.version }}.tar.gz
          openapi-specs-${{ inputs.version }}.tar.gz
          python-client-${{ inputs.version }}.whl
          python-client-${{ inputs.version }}-source.tar.gz
        body: |
          ## Release ${{ inputs.version }}
          
          This release contains generated client libraries for multiple languages:
          
          ### 📦 Available Packages
          
          - **TypeScript/JavaScript**: `typescript-client-${{ inputs.version }}.tar.gz`
          - **Python**: `python-client-${{ inputs.version }}.whl` (wheel) and `python-client-${{ inputs.version }}-source.tar.gz` (source)
          - **Go**: `go-client-${{ inputs.version }}.tar.gz`
          - **OpenAPI**: `openapi-specs-${{ inputs.version }}.tar.gz`
          
          ### 🚀 Usage
          
          **TypeScript/JavaScript**:
          ```bash
          npm install ./typescript-client-${{ inputs.version }}.tar.gz
          ```
          
          **Python**:
          ```bash
          pip install ./python-client-${{ inputs.version }}.whl
          ```
          
          **Go**:
          ```bash
          go get github.com/cyberstorm-dev/attestor-schemas/go@${{ inputs.version }}
          ```
          
          All packages are generated from the same Protocol Buffer schemas and are fully compatible.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}